#!/usr/bin/env node

const test = require('tape');
const bufferEqual = require('buffer-equal');
const WebSocketFrame = require('../../lib/WebSocketFrame');
const utils = require('../../lib/utils');
const bufferAllocUnsafe = utils.bufferAllocUnsafe;
const bufferFromString = utils.bufferFromString;


test('Serializing a WebSocket Frame with no data', function(t) {
  t.plan(2);
  
  // WebSocketFrame uses a per-connection buffer for the mask bytes
  // and the frame header to avoid allocating tons of small chunks of RAM.
  const maskBytesBuffer = bufferAllocUnsafe(4);
  const frameHeaderBuffer = bufferAllocUnsafe(10);
  
  let frameBytes;
  const frame = new WebSocketFrame(maskBytesBuffer, frameHeaderBuffer, {});
  frame.fin = true;
  frame.mask = true;
  frame.opcode = 0x09; // WebSocketFrame.PING
  t.doesNotThrow(
    function() { frameBytes = frame.toBuffer(true); },
    'should not throw an error'
  );
  
  t.assert(
    bufferEqual
      (frameBytes, bufferFromString('898000000000', 'hex')),
    'Generated bytes should be correct'
  );
  
  t.end();
});
