name: websocket-tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
      fail-fast: false
    name: Test on Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpx playwright install --with-deps chromium

      - name: Run lint
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test

      - name: Run browser tests (Chromium only)
        run: pnpm run test:browser:chromium

      - name: Pull Autobahn Test Suite Docker image
        run: docker pull crossbario/autobahn-testsuite

      - name: Run Autobahn WebSocket Protocol Tests
        run: cd test/autobahn && node run-wstest.js
